# Generated by Django 2.2.2 on 2019-07-09 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cantidad',
            fields=[
                ('cantidad_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('flg_activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientePf',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente_ml_email', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente_original_lista_dist', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente_fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('cliente_fecha_activo', models.DateField(blank=True, null=True)),
                ('cliente_flg_autenticado', models.BooleanField(default=False)),
                ('cliente_nombre', models.CharField(max_length=100)),
                ('cliente_apellido', models.CharField(max_length=100)),
                ('cliente_tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('CUIL', 'CUIL'), ('LC', 'LC'), ('LE', 'LE'), ('PASA', 'PASAPORTE')], max_length=10)),
                ('cliente_nro_documento', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='ClientePj',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente_ml_email', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente_original_lista_dist', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente_fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('cliente_fecha_activo', models.DateField(blank=True, null=True)),
                ('cliente_flg_autenticado', models.BooleanField(default=False)),
                ('cliente_razon_social', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente_cuit', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='ColorImpresion',
            fields=[
                ('color_impresion_id', models.AutoField(primary_key=True, serialize=False)),
                ('color_impresion', models.CharField(max_length=50)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('flg_activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ComprobanteCobro',
            fields=[
                ('comprobante_id', models.AutoField(primary_key=True, serialize=False)),
                ('comprobante_fecha_cobro', models.DateTimeField(auto_now_add=True)),
                ('comprobante_monto_cobro', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='DatoContacto',
            fields=[
                ('dato_contacto_id', models.AutoField(primary_key=True, serialize=False)),
                ('dato_contacto_valor', models.CharField(max_length=50)),
                ('tipo_dato_contacto', models.CharField(choices=[('CEL', 'Celular'), ('TEL', 'Teléfono'), ('EMAIL', 'Email')], max_length=50)),
                ('dato_contacto_interno', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dato_contacto_uso', models.CharField(blank=True, choices=[('PERS', 'Personal'), ('LAB', 'Laboral')], max_length=50, null=True)),
                ('dato_contacto_horario_contacto', models.CharField(blank=True, max_length=100)),
                ('dato_contacto_flg_no_llame', models.NullBooleanField()),
                ('dato_contacto_comentarios', models.TextField()),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('flg_activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('domicilio_id', models.AutoField(primary_key=True, serialize=False)),
                ('domicilio_calle', models.CharField(max_length=100)),
                ('domicilio_entre_calle_1', models.CharField(blank=True, max_length=100)),
                ('domicilio_entre_calle_2', models.CharField(blank=True, max_length=100)),
                ('domicilio_entre_calle_3', models.CharField(blank=True, max_length=100)),
                ('domicilio_altura', models.PositiveIntegerField()),
                ('domicilio_latitud', models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True)),
                ('domicilio_longitud', models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('flg_activo', models.BooleanField()),
            ],
            options={
                'ordering': ['domicilio_id'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('estado_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50)),
                ('tipo_estado', models.CharField(choices=[('FINAL', 'Estado final'), ('NO_FINAL', 'Estado no final')], max_length=50)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('flg_activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Impresion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('flg_activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('localidad_id', models.AutoField(primary_key=True, serialize=False)),
                ('localidad', models.CharField(max_length=100)),
                ('localidad_cp', models.PositiveIntegerField()),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('flg_activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MaquinaPliego',
            fields=[
                ('maquina_id', models.AutoField(primary_key=True, serialize=False)),
                ('maquina_marca', models.CharField(max_length=50)),
                ('maquina_descripcion', models.CharField(max_length=100)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('flg_activo', models.BooleanField()),
                ('maquina_pliego_descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('maquina_pliego_ult_cambio_toner', models.DateField(auto_now=True)),
                ('demasia_impresion_mm', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MaquinaPliegoColorImpresion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('flg_activo', models.BooleanField()),
                ('costo_dolar', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='MaquinaTerminacion',
            fields=[
                ('maquina_id', models.AutoField(primary_key=True, serialize=False)),
                ('maquina_marca', models.CharField(max_length=50)),
                ('maquina_descripcion', models.CharField(max_length=100)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('flg_activo', models.BooleanField()),
                ('maquina_terminacion_descripcion', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaquinaTerminacionTerminaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_max', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('cant_max_costo_dolar', models.DecimalField(decimal_places=3, max_digits=5)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('flg_activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('material', models.CharField(max_length=100)),
                ('material_alto_mm', models.IntegerField()),
                ('material_ancho_mm', models.IntegerField()),
                ('material_costo_dolar', models.DecimalField(decimal_places=3, max_digits=10)),
                ('material_gramaje_grs', models.IntegerField(blank=True, null=True)),
                ('material_demasia_hoja_mm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('flg_activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MedidaEstandar',
            fields=[
                ('medida_estandar_id', models.AutoField(primary_key=True, serialize=False)),
                ('medida_1_cm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medida_2_cm', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('flg_activo', models.BooleanField()),
            ],
            options={
                'ordering': ['medida_1_cm', 'medida_2_cm'],
            },
        ),
        migrations.CreateModel(
            name='ModoEnvio',
            fields=[
                ('modo_envio_id', models.AutoField(primary_key=True, serialize=False)),
                ('modo_envio', models.CharField(max_length=50)),
                ('modo_envio_costo_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('modo_envio_hs_aprox', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('flg_activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('orden_id', models.AutoField(primary_key=True, serialize=False)),
                ('orden_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('orden_precio_final', models.DecimalField(decimal_places=2, max_digits=6)),
                ('orden_express_flg', models.BooleanField()),
                ('orden_impresion_realizada_flg', models.BooleanField()),
                ('orden_terminacion_realizada_flg', models.BooleanField()),
                ('orden_disenio_realizado_flg', models.BooleanField()),
                ('orden_comentarios', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTrabajoEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio_estado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('pais_id', models.AutoField(primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=100)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('flg_activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('cel', models.CharField(blank=True, max_length=20, null=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('CUIL', 'CUIL'), ('LC', 'LC'), ('LE', 'LE'), ('CUIT', 'CUIT'), ('PASA', 'PASAPORTE')], max_length=10)),
                ('numero_documento', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presupuesto_ganancia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('presupuesto_hojas_utilizadas', models.IntegerField()),
                ('presupuesto_precio_dolar', models.DecimalField(decimal_places=3, max_digits=5)),
                ('presupuesto_costo_materiales', models.DecimalField(decimal_places=3, max_digits=6)),
                ('presupuesto_costo_disenio', models.DecimalField(decimal_places=3, max_digits=6)),
                ('presupuesto_costo_unitario', models.DecimalField(decimal_places=3, max_digits=6)),
                ('presupuesto_precio_cliente', models.DecimalField(decimal_places=3, max_digits=6)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PresupuestoTerminaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_dolar', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('proveedor_id', models.AutoField(primary_key=True, serialize=False)),
                ('proveedor_razon_social', models.CharField(max_length=100)),
                ('proveedor_tipo_doc', models.CharField(blank=True, choices=[('DNI', 'DNI'), ('CUIL', 'CUIL'), ('LC', 'LC'), ('LE', 'LE'), ('CUIT', 'CUIT'), ('PASA', 'PASAPORTE')], max_length=10, null=True)),
                ('proveedor_nro_doc', models.CharField(blank=True, max_length=12, null=True)),
                ('proveedor_descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('nota_1', models.TextField(blank=True, null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('flg_activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('provincia_id', models.AutoField(primary_key=True, serialize=False)),
                ('provincia', models.CharField(max_length=100)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('flg_activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ServicioTecnico',
            fields=[
                ('servicio_tecnico_id', models.AutoField(primary_key=True, serialize=False)),
                ('servicio_tecnico', models.CharField(max_length=100)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('flg_activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudPresupuesto',
            fields=[
                ('solicitud_id', models.AutoField(primary_key=True, serialize=False)),
                ('solicitud_fecha', models.DateTimeField(auto_now_add=True)),
                ('solicitud_disenio_flg', models.BooleanField()),
                ('solicitud_trabajo_alto_mm', models.IntegerField()),
                ('solicitud_trabajo_ancho_mm', models.IntegerField()),
                ('solicitud_terminacion_flg', models.BooleanField()),
                ('solicitud_fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('solicitud_express_flg', models.BooleanField()),
                ('solicitud_doble_cara_impresion_flg', models.BooleanField()),
                ('solicitud_adjuntos', models.FilePathField()),
                ('solicitud_orientacion', models.CharField(blank=True, choices=[('V', 'Vertical'), ('H', 'Horizontal')], max_length=5, null=True)),
                ('solicitud_email_enviado_flg', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudPresupuestoTerminaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doble_cara_flg', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Terminacion',
            fields=[
                ('terminacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('terminacion', models.CharField(max_length=100)),
                ('terminacion_tiempo_seg', models.PositiveSmallIntegerField()),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('flg_activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('tipo_cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_cliente', models.CharField(max_length=50)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('flg_activo', models.BooleanField()),
            ],
            options={
                'ordering': ['tipo_cliente_id'],
            },
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('tipo_pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_pago', models.CharField(max_length=50)),
                ('tipo_pago_recargo_porcentaje', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('flg_activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoTerminacion',
            fields=[
                ('tipo_terminacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_terminacion', models.CharField(max_length=50)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('flg_activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoTrabajo',
            fields=[
                ('tipo_trabajo_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_trabajo', models.CharField(max_length=50)),
                ('tipo_trabajo_autoadhesivo_flg', models.BooleanField()),
                ('tipo_trabajo_doble_cara_flg', models.BooleanField()),
                ('tipo_trabajo_tiempo_aprox_hs', models.IntegerField(blank=True, null=True)),
                ('tipo_trabajo_demasia_trabajo_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_trabajo_circular_flg', models.BooleanField()),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('flg_activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoTrabajoMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('flg_activo', models.BooleanField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_material', to='gestion_imprenta.Material')),
                ('tipo_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.TipoTrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoTrabajoCantidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('flg_activo', models.BooleanField()),
                ('cantidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.Cantidad')),
                ('tipo_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.TipoTrabajo')),
            ],
        ),
        migrations.AddField(
            model_name='tipotrabajo',
            name='cantidades',
            field=models.ManyToManyField(through='gestion_imprenta.TipoTrabajoCantidades', to='gestion_imprenta.Cantidad'),
        ),
        migrations.AddField(
            model_name='tipotrabajo',
            name='medidas',
            field=models.ManyToManyField(to='gestion_imprenta.MedidaEstandar'),
        ),
        migrations.AddConstraint(
            model_name='tipoterminacion',
            constraint=models.UniqueConstraint(fields=('tipo_terminacion', 'fecha_carga', 'flg_activo'), name='unique_tipo_terminacion'),
        ),
        migrations.AddConstraint(
            model_name='tipopago',
            constraint=models.UniqueConstraint(fields=('tipo_pago', 'fecha_carga', 'flg_activo'), name='unique_tipo_pago'),
        ),
        migrations.AddConstraint(
            model_name='tipocliente',
            constraint=models.UniqueConstraint(fields=('tipo_cliente',), name='unique_tipo_cliente'),
        ),
        migrations.AddField(
            model_name='terminacion',
            name='tipo_terminacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.TipoTerminacion'),
        ),
        migrations.AddField(
            model_name='solicitudpresupuestoterminaciones',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.SolicitudPresupuesto'),
        ),
        migrations.AddField(
            model_name='solicitudpresupuestoterminaciones',
            name='terminacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.Terminacion'),
        ),
        migrations.AddField(
            model_name='solicitudpresupuesto',
            name='cliente_pf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.ClientePf'),
        ),
        migrations.AddField(
            model_name='solicitudpresupuesto',
            name='cliente_pj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.ClientePj'),
        ),
        migrations.AddField(
            model_name='solicitudpresupuesto',
            name='color_impresion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.ColorImpresion'),
        ),
        migrations.AddField(
            model_name='solicitudpresupuesto',
            name='envio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.ModoEnvio'),
        ),
        migrations.AddField(
            model_name='solicitudpresupuesto',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.Material'),
        ),
        migrations.AddField(
            model_name='solicitudpresupuesto',
            name='tipo_trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.TipoTrabajo'),
        ),
        migrations.AddConstraint(
            model_name='serviciotecnico',
            constraint=models.UniqueConstraint(fields=('servicio_tecnico', 'fecha_carga', 'flg_activo'), name='unique_service'),
        ),
        migrations.AddField(
            model_name='provincia',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.Pais'),
        ),
        migrations.AddConstraint(
            model_name='proveedor',
            constraint=models.UniqueConstraint(fields=('proveedor_razon_social',), name='unique_proveedor'),
        ),
        migrations.AddConstraint(
            model_name='proveedor',
            constraint=models.UniqueConstraint(fields=('proveedor_tipo_doc', 'proveedor_nro_doc'), name='unique_tipo_nro_doc_proveedor'),
        ),
        migrations.AddField(
            model_name='presupuestoterminaciones',
            name='maquina_terminacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.MaquinaTerminacion'),
        ),
        migrations.AddField(
            model_name='presupuestoterminaciones',
            name='presupuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.Presupuesto'),
        ),
        migrations.AddField(
            model_name='presupuestoterminaciones',
            name='terminacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.Terminacion'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='maquina_pliego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.MaquinaPliego'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.SolicitudPresupuesto'),
        ),
        migrations.AddField(
            model_name='personal',
            name='user_id',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='personal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='pais',
            constraint=models.UniqueConstraint(fields=('pais',), name='unique_pais'),
        ),
        migrations.AddField(
            model_name='ordentrabajoestado',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.Estado'),
        ),
        migrations.AddField(
            model_name='ordentrabajoestado',
            name='orden_trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.OrdenTrabajo'),
        ),
        migrations.AddField(
            model_name='ordentrabajoestado',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.Personal'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='estados',
            field=models.ManyToManyField(through='gestion_imprenta.OrdenTrabajoEstado', to='gestion_imprenta.Estado'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.SolicitudPresupuesto'),
        ),
        migrations.AddConstraint(
            model_name='modoenvio',
            constraint=models.UniqueConstraint(fields=('modo_envio', 'fecha_carga', 'flg_activo'), name='unique_modo_envio'),
        ),
        migrations.AddConstraint(
            model_name='medidaestandar',
            constraint=models.UniqueConstraint(fields=('medida_1_cm', 'medida_2_cm'), name='unique_medida_estandar'),
        ),
        migrations.AddField(
            model_name='material',
            name='proveedores',
            field=models.ManyToManyField(blank=True, related_name='material', to='gestion_imprenta.Proveedor'),
        ),
        migrations.AddField(
            model_name='material',
            name='trabajos',
            field=models.ManyToManyField(blank=True, through='gestion_imprenta.TipoTrabajoMaterial', to='gestion_imprenta.TipoTrabajo'),
        ),
        migrations.AddField(
            model_name='maquinaterminacionterminaciones',
            name='maquina_terminacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.MaquinaTerminacion'),
        ),
        migrations.AddField(
            model_name='maquinaterminacionterminaciones',
            name='terminacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.Terminacion'),
        ),
        migrations.AddField(
            model_name='maquinaterminacion',
            name='terminaciones',
            field=models.ManyToManyField(through='gestion_imprenta.MaquinaTerminacionTerminaciones', to='gestion_imprenta.Terminacion'),
        ),
        migrations.AddField(
            model_name='maquinapliegocolorimpresion',
            name='color_impresion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.ColorImpresion'),
        ),
        migrations.AddField(
            model_name='maquinapliegocolorimpresion',
            name='maquina_pliego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.MaquinaPliego'),
        ),
        migrations.AddField(
            model_name='maquinapliego',
            name='colores_impresion',
            field=models.ManyToManyField(through='gestion_imprenta.MaquinaPliegoColorImpresion', to='gestion_imprenta.ColorImpresion'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='pronvincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.Provincia'),
        ),
        migrations.AddField(
            model_name='impresion',
            name='color_impresion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.ColorImpresion'),
        ),
        migrations.AddField(
            model_name='impresion',
            name='maquina_pliego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.MaquinaPliego'),
        ),
        migrations.AddField(
            model_name='impresion',
            name='tipo_trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.TipoTrabajo'),
        ),
        migrations.AddConstraint(
            model_name='estado',
            constraint=models.UniqueConstraint(fields=('estado', 'fecha_carga', 'flg_activo'), name='unique_estado'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='cliente_pf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.ClientePf'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='cliente_pj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.ClientePj'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.Localidad'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.Pais'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.Proveedor'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.Provincia'),
        ),
        migrations.AddField(
            model_name='datocontacto',
            name='cliente_pf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_imprenta.ClientePf'),
        ),
        migrations.AddField(
            model_name='datocontacto',
            name='cliente_pj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_imprenta.ClientePj'),
        ),
        migrations.AddField(
            model_name='datocontacto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_imprenta.Proveedor'),
        ),
        migrations.AddField(
            model_name='datocontacto',
            name='servicio_tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_imprenta.ServicioTecnico'),
        ),
        migrations.AddField(
            model_name='comprobantecobro',
            name='tipo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.TipoPago'),
        ),
        migrations.AddConstraint(
            model_name='colorimpresion',
            constraint=models.UniqueConstraint(fields=('color_impresion', 'fecha_carga', 'flg_activo'), name='unique_color'),
        ),
        migrations.AddField(
            model_name='clientepj',
            name='tipo_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.TipoCliente'),
        ),
        migrations.AddField(
            model_name='clientepf',
            name='tipo_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.TipoCliente'),
        ),
        migrations.AddConstraint(
            model_name='cantidad',
            constraint=models.UniqueConstraint(fields=('cantidad', 'fecha_carga', 'flg_activo'), name='unique_cantidad'),
        ),
        migrations.AddConstraint(
            model_name='tipotrabajomaterial',
            constraint=models.UniqueConstraint(fields=('tipo_trabajo', 'material', 'fecha_carga', 'flg_activo'), name='unique_tipo_trabajo_material_activo'),
        ),
        migrations.AddConstraint(
            model_name='tipotrabajocantidades',
            constraint=models.UniqueConstraint(fields=('tipo_trabajo', 'cantidad', 'descuento', 'fecha_carga', 'flg_activo'), name='unique_tipo_trabajo_cantidad'),
        ),
        migrations.AddConstraint(
            model_name='tipotrabajo',
            constraint=models.UniqueConstraint(fields=('tipo_trabajo',), name='unique_tipo_trabajo'),
        ),
        migrations.AddConstraint(
            model_name='terminacion',
            constraint=models.UniqueConstraint(fields=('terminacion', 'tipo_terminacion', 'fecha_carga', 'flg_activo'), name='unique_terminacion'),
        ),
        migrations.AddConstraint(
            model_name='solicitudpresupuestoterminaciones',
            constraint=models.UniqueConstraint(fields=('solicitud', 'terminacion', 'doble_cara_flg'), name='unique_solcitud_terminaciones'),
        ),
        migrations.AddConstraint(
            model_name='provincia',
            constraint=models.UniqueConstraint(fields=('provincia',), name='unique_provincia'),
        ),
        migrations.AddConstraint(
            model_name='personal',
            constraint=models.UniqueConstraint(fields=('tipo_documento', 'numero_documento'), name='unique_tipo_nro_doc_personal'),
        ),
        migrations.AddConstraint(
            model_name='ordentrabajo',
            constraint=models.UniqueConstraint(fields=('solicitud',), name='unique_ot'),
        ),
        migrations.AddConstraint(
            model_name='maquinaterminacionterminaciones',
            constraint=models.UniqueConstraint(fields=('maquina_terminacion', 'terminacion', 'cant_max', 'fecha_carga', 'flg_activo'), name='unique_maq_terminacion_terminaciones'),
        ),
        migrations.AddConstraint(
            model_name='maquinaterminacion',
            constraint=models.UniqueConstraint(fields=('maquina_terminacion_descripcion', 'fecha_carga', 'flg_activo'), name='unique_maq_terminacion'),
        ),
        migrations.AddConstraint(
            model_name='maquinapliegocolorimpresion',
            constraint=models.UniqueConstraint(fields=('maquina_pliego', 'color_impresion', 'fecha_carga', 'flg_activo'), name='unique_pliego_color'),
        ),
        migrations.AddConstraint(
            model_name='maquinapliego',
            constraint=models.UniqueConstraint(fields=('maquina_pliego_descripcion', 'fecha_carga', 'flg_activo'), name='unique_maq_pliego'),
        ),
        migrations.AddConstraint(
            model_name='localidad',
            constraint=models.UniqueConstraint(fields=('localidad', 'localidad_cp'), name='unique_cp_localidad'),
        ),
        migrations.AddConstraint(
            model_name='localidad',
            constraint=models.UniqueConstraint(fields=('localidad',), name='unique_localidad'),
        ),
        migrations.AddConstraint(
            model_name='impresion',
            constraint=models.UniqueConstraint(fields=('tipo_trabajo', 'color_impresion', 'maquina_pliego', 'fecha_carga', 'flg_activo'), name='unique_impresion'),
        ),
        migrations.AddConstraint(
            model_name='domicilio',
            constraint=models.UniqueConstraint(fields=('cliente_pj', 'domicilio_calle', 'domicilio_altura'), name='unique_domicilio_cliente_pj'),
        ),
        migrations.AddConstraint(
            model_name='datocontacto',
            constraint=models.UniqueConstraint(fields=('dato_contacto_valor', 'tipo_dato_contacto', 'cliente_pf'), name='unique_dc_cliente_pf'),
        ),
        migrations.AddConstraint(
            model_name='datocontacto',
            constraint=models.UniqueConstraint(fields=('dato_contacto_valor', 'tipo_dato_contacto', 'cliente_pj'), name='unique_dc_cliente_pj'),
        ),
        migrations.AddConstraint(
            model_name='clientepj',
            constraint=models.UniqueConstraint(fields=('cliente_cuit',), name='unique_cuit'),
        ),
        migrations.AddConstraint(
            model_name='clientepf',
            constraint=models.UniqueConstraint(fields=('cliente_tipo_documento', 'cliente_nro_documento'), name='unique_tipo_nro_doc'),
        ),
    ]
