# Generated by Django 2.2.2 on 2019-07-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cantidad',
            name='unique_cantidad',
        ),
        migrations.AddConstraint(
            model_name='cantidad',
            constraint=models.UniqueConstraint(fields=('cantidad',), name='unique_cantidad'),
        ),
    ]
