# Generated by Django 2.2.2 on 2019-07-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0002_auto_20190709_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantidad',
            name='cantidad',
            field=models.IntegerField(error_messages={'unique': 'Esta cantidad ya existe'}, unique=True),
        ),
    ]
