# Generated by Django 2.2.2 on 2019-07-09 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0003_auto_20190709_2101'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cantidad',
            name='unique_cantidad',
        ),
    ]
