# Generated by Django 2.2.2 on 2019-07-09 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0004_auto_20190709_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientepj',
            options={'ordering': ['cliente_id']},
        ),
        migrations.AlterModelOptions(
            name='maquinaterminacion',
            options={'ordering': ['maquina_id']},
        ),
        migrations.RemoveConstraint(
            model_name='clientepj',
            name='unique_cuit',
        ),
        migrations.RemoveConstraint(
            model_name='colorimpresion',
            name='unique_color',
        ),
        migrations.RemoveConstraint(
            model_name='estado',
            name='unique_estado',
        ),
        migrations.RemoveConstraint(
            model_name='localidad',
            name='unique_localidad',
        ),
        migrations.RemoveConstraint(
            model_name='maquinaterminacion',
            name='unique_maq_terminacion',
        ),
        migrations.RemoveConstraint(
            model_name='modoenvio',
            name='unique_modo_envio',
        ),
        migrations.RemoveConstraint(
            model_name='ordentrabajo',
            name='unique_ot',
        ),
        migrations.RemoveConstraint(
            model_name='pais',
            name='unique_pais',
        ),
        migrations.RemoveConstraint(
            model_name='proveedor',
            name='unique_proveedor',
        ),
        migrations.RemoveConstraint(
            model_name='provincia',
            name='unique_provincia',
        ),
        migrations.RemoveConstraint(
            model_name='terminacion',
            name='unique_terminacion',
        ),
        migrations.RemoveConstraint(
            model_name='tipocliente',
            name='unique_tipo_cliente',
        ),
        migrations.RemoveConstraint(
            model_name='tipopago',
            name='unique_tipo_pago',
        ),
        migrations.RemoveConstraint(
            model_name='tipoterminacion',
            name='unique_tipo_terminacion',
        ),
        migrations.RemoveConstraint(
            model_name='tipotrabajo',
            name='unique_tipo_trabajo',
        ),
        migrations.RemoveConstraint(
            model_name='tipotrabajomaterial',
            name='unique_tipo_trabajo_material_activo',
        ),
        migrations.AlterField(
            model_name='clientepj',
            name='cliente_cuit',
            field=models.CharField(error_messages={'unique': 'Este CUIT ya existe'}, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='colorimpresion',
            name='color_impresion',
            field=models.CharField(error_messages={'unique': 'Este color de impresión ya existe'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.CharField(error_messages={'unique': 'Este estado ya está registrado'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='maquinaterminacion',
            name='maquina_terminacion_descripcion',
            field=models.CharField(blank=True, error_messages={'unique': 'Esta maquina terminación ya existe'}, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='modoenvio',
            name='modo_envio',
            field=models.CharField(error_messages={'unique': 'Este modo de envío ya existe'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='solicitud',
            field=models.ForeignKey(error_messages={'unique': 'Ya existe una Orden de trabajo para esta solicitud'}, on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.SolicitudPresupuesto', unique=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='pais',
            field=models.CharField(error_messages={'unique': 'Este país ya fue ingresado'}, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='provincia',
            field=models.CharField(error_messages={'unique': 'Esta provincia ya fue ingresada'}, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='terminacion',
            name='terminacion',
            field=models.CharField(error_messages={'unique': 'Esta terminación ya existe'}, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tipocliente',
            name='tipo_cliente',
            field=models.CharField(error_messages={'unique': 'Este tipo de cliente ya existe'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tipopago',
            name='tipo_pago',
            field=models.CharField(error_messages={'unique': 'Este tipo de pago ya existe'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tipoterminacion',
            name='tipo_terminacion',
            field=models.CharField(error_messages={'unique': 'Este tipo de terminación ya existe'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tipotrabajo',
            name='tipo_trabajo',
            field=models.CharField(error_messages={'unique': 'Este tipo de trabajo ya existe'}, max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(fields=('material', 'material_alto_mm', 'material_ancho_mm', 'material_gramaje_grs', 'material_costo_dolar'), name='unique_material'),
        ),
        migrations.AddConstraint(
            model_name='tipotrabajomaterial',
            constraint=models.UniqueConstraint(fields=('tipo_trabajo', 'material'), name='unique_tipo_trabajo_material_activo'),
        ),
    ]
