# Generated by Django 2.2.2 on 2019-07-09 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0006_auto_20190709_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cantidad',
            options={'ordering': ['cantidad']},
        ),
    ]
