# Generated by Django 2.2.2 on 2019-07-09 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0007_auto_20190709_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='trabajos',
        ),
        migrations.DeleteModel(
            name='TipoTrabajoMaterial',
        ),
    ]
