# Generated by Django 2.2.2 on 2019-07-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0008_auto_20190709_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipotrabajo',
            name='materiales',
            field=models.ManyToManyField(to='gestion_imprenta.Material'),
        ),
    ]
