# Generated by Django 2.2.2 on 2019-07-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0009_tipotrabajo_materiales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datocontacto',
            name='dato_contacto_comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
