# Generated by Django 2.2.2 on 2019-07-21 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0010_auto_20190721_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datocontacto',
            name='dato_contacto_interno',
        ),
    ]
