# Generated by Django 2.2.2 on 2019-07-21 23:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0011_remove_datocontacto_dato_contacto_interno'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantecobro',
            name='fecha_carga',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
