# Generated by Django 2.2.2 on 2019-07-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0012_comprobantecobro_fecha_carga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudpresupuesto',
            name='solicitud_adjuntos',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='terminacion',
            name='tipo_terminacion',
            field=models.CharField(choices=[('ABROCHADO', 'Abrochado'), ('CORTE', 'Corte'), ('IMPRESION', 'Impresión'), ('LAMINADO', 'Laminado')], max_length=100),
        ),
        migrations.DeleteModel(
            name='TipoTerminacion',
        ),
    ]
