# Generated by Django 2.2.2 on 2019-07-22 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0013_auto_20190722_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='orden_express_flg',
        ),
    ]
