# Generated by Django 2.2.2 on 2021-02-14 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0032_auto_20210207_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudpresupuesto',
            name='solicitud_apellido',
        ),
        migrations.RemoveField(
            model_name='solicitudpresupuesto',
            name='solicitud_email',
        ),
        migrations.RemoveField(
            model_name='solicitudpresupuesto',
            name='solicitud_nombre',
        ),
        migrations.AddField(
            model_name='solicitudpresupuesto',
            name='solicitud_contacto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.Contacto'),
            preserve_default=False,
        ),
    ]
