# Generated by Django 2.2.2 on 2021-02-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0034_auto_20210215_0026'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cliente',
            name='unique_email',
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='email_idx',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cliente_email_contacto',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cliente_origen',
            field=models.CharField(choices=[('formulario_presupuesto', 'Formulario de Presupuesto'), ('manual', 'Manual')], default='formulario_presupuesto', max_length=25),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='flg_activo',
            field=models.BooleanField(default=True),
        ),
    ]
