# Generated by Django 2.2.2 on 2021-02-26 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0035_auto_20210226_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudpresupuesto',
            old_name='solicitud_contacto',
            new_name='contacto',
        ),
    ]
