# Generated by Django 2.2.2 on 2021-02-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0036_auto_20210226_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='tipo_dato_contacto',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('TEL_CEL', 'Tel / Cel')], default='EMAIL', max_length=25),
        ),
        migrations.DeleteModel(
            name='TipoContacto',
        ),
    ]
