# Generated by Django 2.2.2 on 2021-03-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0040_auto_20210307_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidaestandar',
            name='medida_2_cm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
