# Generated by Django 2.2.2 on 2021-03-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0041_auto_20210307_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinapliego',
            name='flg_activo',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='maquinaterminacion',
            name='flg_activo',
            field=models.BooleanField(blank=True),
        ),
    ]
