# Generated by Django 2.2.2 on 2021-03-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0042_auto_20210313_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinapliegocolores',
            name='flg_activo',
            field=models.BooleanField(blank=True),
        ),
    ]
