# Generated by Django 2.2.2 on 2021-03-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0043_auto_20210313_2244'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='maquinapliegocolores',
            name='unique_pliego_color',
        ),
        migrations.AddConstraint(
            model_name='maquinapliegocolores',
            constraint=models.UniqueConstraint(fields=('maquina_pliego', 'color_impresion', 'flg_activo'), name='unique_pliego_color'),
        ),
    ]
