# Generated by Django 2.2.2 on 2021-03-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0044_auto_20210314_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinapliegocolores',
            name='costo_dolar',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
