# Generated by Django 2.2.2 on 2021-03-14 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0045_auto_20210314_1134'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trabajo',
            table='"trabajo"',
        ),
    ]
