# Generated by Django 2.2.2 on 2021-03-14 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0047_auto_20210314_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajoterminaciones',
            old_name='tipo_trabajo',
            new_name='trabajo',
        ),
    ]
