# Generated by Django 2.2.2 on 2021-03-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0048_auto_20210314_1358'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trabajoterminaciones',
            name='unique_tipo_trabajo_terminacion',
        ),
        migrations.AddConstraint(
            model_name='trabajoterminaciones',
            constraint=models.UniqueConstraint(fields=('trabajo', 'terminacion', 'flg_activo'), name='unique_trabajo_terminacion'),
        ),
        migrations.AlterModelTable(
            name='trabajoterminaciones',
            table='"trabajo_terminaciones"',
        ),
    ]
