# Generated by Django 2.2.2 on 2021-03-14 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0049_auto_20210314_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='fecha_carga',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='envio',
            name='flg_activo',
            field=models.BooleanField(blank=True, default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='envio',
            name='modo_envio',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddConstraint(
            model_name='envio',
            constraint=models.UniqueConstraint(fields=('modo_envio', 'flg_activo'), name='unique_modo_envio'),
        ),
    ]
