# Generated by Django 2.2.2 on 2021-03-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0050_auto_20210314_1530'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='estado',
            name='unique_tipo_estado',
        ),
        migrations.AddConstraint(
            model_name='estado',
            constraint=models.UniqueConstraint(fields=('estado', 'tipo_estado', 'flg_activo'), name='unique_tipo_estado'),
        ),
    ]
