# Generated by Django 2.2.2 on 2021-03-14 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0051_auto_20210314_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subestado',
            fields=[
                ('subestado_id', models.AutoField(primary_key=True, serialize=False)),
                ('subestado', models.CharField(max_length=50)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('flg_activo', models.BooleanField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.Estado')),
            ],
            options={
                'db_table': '"subestado"',
            },
        ),
        migrations.AddConstraint(
            model_name='subestado',
            constraint=models.UniqueConstraint(fields=('estado', 'subestado', 'flg_activo'), name='unique_subestado'),
        ),
    ]
