# Generated by Django 2.2.2 on 2021-03-14 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0052_auto_20210314_1552'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='terminacion',
            name='unique_terminacion',
        ),
        migrations.RemoveConstraint(
            model_name='tipoterminacion',
            name='unique_tipo_terminacion',
        ),
        migrations.AddField(
            model_name='tipoterminacion',
            name='fecha_carga',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipoterminacion',
            name='flg_activo',
            field=models.BooleanField(blank=True, default=True),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='terminacion',
            constraint=models.UniqueConstraint(fields=('terminacion', 'flg_activo'), name='unique_terminacion'),
        ),
        migrations.AddConstraint(
            model_name='tipoterminacion',
            constraint=models.UniqueConstraint(fields=('tipo_terminacion', 'flg_activo'), name='unique_tipo_terminacion'),
        ),
    ]
