# Generated by Django 2.2.2 on 2021-03-14 21:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0053_auto_20210314_1944'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='terminacionesmaquinas',
            name='unique_maq_terminacion_terminaciones',
        ),
        migrations.AddField(
            model_name='terminacionesmaquinas',
            name='fecha_carga',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terminacionesmaquinas',
            name='flg_activo',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='terminacionesmaquinas',
            constraint=models.UniqueConstraint(fields=('maquina_terminacion', 'terminacion', 'flg_activo'), name='unique_maq_terminacion_terminaciones'),
        ),
    ]
