# Generated by Django 2.2.2 on 2021-03-22 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_imprenta', '0056_auto_20210321_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, max_length=100)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.OrdenTrabajo')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.Presupuesto')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.SolicitudPresupuesto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
