# Generated by Django 2.2.2 on 2021-03-22 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0057_comentarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudpresupuesto',
            name='solicitud_comentarios_internos',
        ),
    ]
