# Generated by Django 2.2.2 on 2021-03-22 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0058_remove_solicitudpresupuesto_solicitud_comentarios_internos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='orden_comentarios',
        ),
    ]
