# Generated by Django 2.2.2 on 2021-03-23 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0060_auto_20210322_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='orden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.OrdenTrabajo'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='presupuesto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.Presupuesto'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='solicitud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.SolicitudPresupuesto'),
        ),
    ]
