# Generated by Django 2.2.2 on 2021-03-23 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0062_auto_20210323_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudpresupuesto',
            old_name='maquina_pliego_id',
            new_name='maquina_pliego',
        ),
    ]
