# Generated by Django 2.2.2 on 2021-03-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0063_auto_20210323_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudpresupuesto',
            name='solicitud_email_enviado_flg',
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='presupuesto_aceptado_flg',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='presupuesto_comentarios_rechazo',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='presupuesto_enviado_flg',
            field=models.BooleanField(default=False),
        ),
    ]
