# Generated by Django 2.2.2 on 2021-03-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0064_auto_20210323_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='presupuesto_impresion',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
