# Generated by Django 2.2.2 on 2021-03-24 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0065_presupuesto_presupuesto_impresion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='presupuesto_costo_materiales',
        ),
    ]
