# Generated by Django 2.2.2 on 2021-03-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0066_remove_presupuesto_presupuesto_costo_materiales'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='presupuesto_costo_material',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
