# Generated by Django 2.2.2 on 2021-03-24 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0068_auto_20210324_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudpresupuesto',
            name='cantidad_hojas_estimadas',
        ),
    ]
