# Generated by Django 2.2.2 on 2021-03-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0069_remove_solicitudpresupuesto_cantidad_hojas_estimadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='presupuesto_precio_dolar',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
