# Generated by Django 2.2.2 on 2021-03-25 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0074_auto_20210325_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presupuesto',
            old_name='presupuesto_cliente',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='presupuesto',
            old_name='presupuesto_costo_disenio',
            new_name='costo_disenio',
        ),
        migrations.RenameField(
            model_name='presupuesto',
            old_name='presupuesto_costo_impresion',
            new_name='costo_impresion_dolar',
        ),
        migrations.RenameField(
            model_name='presupuesto',
            old_name='presupuesto_costo_material',
            new_name='costo_material_dolar',
        ),
        migrations.RenameField(
            model_name='presupuesto',
            old_name='presupuesto_costo_terminaciones',
            new_name='costo_terminaciones_dolar',
        ),
        migrations.RenameField(
            model_name='presupuesto',
            old_name='presupuesto_costo_unitario',
            new_name='costo_unitario_dolar',
        ),
        migrations.RenameField(
            model_name='presupuesto',
            old_name='presupuesto_precio_dolar',
            new_name='cotizacion_dolar',
        ),
        migrations.RenameField(
            model_name='presupuesto',
            old_name='presupuesto_hojas_utilizadas',
            new_name='hojas_utilizadas',
        ),
        migrations.RenameField(
            model_name='presupuesto',
            old_name='presupuesto_porc_ganancia',
            new_name='margen_ganancia',
        ),
        migrations.RenameField(
            model_name='presupuesto',
            old_name='presupuesto_precio_cliente',
            new_name='precio_cliente',
        ),
    ]
