# Generated by Django 2.2.2 on 2021-03-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0075_auto_20210325_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='costo_total_dolar',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
