# Generated by Django 2.2.2 on 2021-03-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0076_presupuesto_costo_total_dolar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='costo_disenio',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
