# Generated by Django 2.2.2 on 2021-03-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0077_auto_20210326_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='costo_total_dolar',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='precio_cliente',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
