# Generated by Django 2.2.2 on 2021-03-26 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0078_auto_20210326_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presupuesto',
            options={'ordering': ['-fecha_carga']},
        ),
        migrations.RemoveConstraint(
            model_name='personal',
            name='unique_tipo_nro_doc_personal',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='numero_documento',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='tipo_documento',
        ),
    ]
