# Generated by Django 2.2.2 on 2021-03-26 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0079_auto_20210326_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='tel',
        ),
    ]
