# Generated by Django 2.2.2 on 2021-03-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0081_auto_20210326_2131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['cliente_id'], 'permissions': [('elegir_origen', 'Elegir origen del cliente')]},
        ),
        migrations.AlterModelOptions(
            name='domicilio',
            options={'permissions': [('agregar_laitud', 'Agregar Latitud'), ('agregar_longitud', 'Agregar Longitud')]},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'permissions': [('cambiar_flg_activo', 'Cambiar flg activo')]},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_origen',
            field=models.CharField(choices=[('formulario_presupuesto', 'Formulario de Presupuesto'), ('manual', 'Manual')], default='manual', max_length=25),
        ),
    ]
