# Generated by Django 2.2.2 on 2021-03-27 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0083_auto_20210327_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudpresupuesto',
            name='contacto',
        ),
        migrations.AddField(
            model_name='solicitudpresupuesto',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.Cliente'),
            preserve_default=False,
        ),
    ]
