# Generated by Django 2.2.2 on 2021-03-27 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0084_auto_20210327_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudpresupuesto',
            name='cliente',
        ),
        migrations.AddField(
            model_name='solicitudpresupuesto',
            name='contacto',
            field=models.ForeignKey(default=240, on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.Contacto'),
            preserve_default=False,
        ),
    ]
