# Generated by Django 2.2.2 on 2021-03-27 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_imprenta', '0085_auto_20210327_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='fecha_envio_presupuesto',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='presupuesto_aceptado_flg',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='presupuesto_comentarios_rechazo',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='presupuesto_enviado_flg',
        ),
        migrations.CreateModel(
            name='PresupuestoEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('creado', 'Creado'), ('enviado', 'Enviado'), ('aceptado_cliente', 'Aceptado por el cliente'), ('rechazado_cliente', 'Rechazado por el cliente'), ('cancelado', 'Cancelado'), ('cancelado_por_otra_aceptacion', 'Cancelado por otro aceptado')], max_length=50)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.Presupuesto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"presupuesto_estados"',
            },
        ),
    ]
