# Generated by Django 2.2.2 on 2021-03-27 23:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0086_auto_20210327_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestoestado',
            name='fecha_cambio_estado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
