# Generated by Django 2.2.2 on 2021-04-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0088_auto_20210328_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='estado_secuencia',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
