# Generated by Django 2.2.2 on 2021-04-02 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0089_estado_estado_secuencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presupuestoestado',
            options={'ordering': ['presupuesto', '-fecha_cambio_estado']},
        ),
    ]
