# Generated by Django 2.2.2 on 2021-04-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0091_estado_entidad_asociada'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='estado',
            name='unique_tipo_estado',
        ),
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name='estado',
            constraint=models.UniqueConstraint(fields=('estado', 'tipo_estado', 'flg_activo', 'entidad_asociada'), name='unique_tipo_estado'),
        ),
    ]
