# Generated by Django 2.2.2 on 2021-04-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0093_auto_20210402_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='tipo_estado',
            field=models.CharField(choices=[('Final', 'Estado final'), ('Intermedio', 'Estado intermedio'), ('Inicial', 'Estado inicial')], max_length=25),
        ),
        migrations.AddConstraint(
            model_name='estado',
            constraint=models.UniqueConstraint(fields=('estado', 'tipo_estado', 'flg_activo', 'estado_secuencia', 'entidad_asociada'), name='unique_tipo_estado'),
        ),
    ]
