# Generated by Django 2.2.2 on 2021-04-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0095_auto_20210403_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estado',
            old_name='estado',
            new_name='estado_descripcion',
        )
    ]
