# Generated by Django 2.2.2 on 2021-04-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0096_auto_20210403_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='orden_disenio_realizado_flg',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='orden_impresion_realizada_flg',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='orden_terminacion_realizada_flg',
            field=models.BooleanField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='estado',
            constraint=models.UniqueConstraint(fields=('estado_descripcion', 'tipo_estado', 'flg_activo', 'estado_secuencia', 'entidad_asociada'), name='unique_tipo_estado'),
        ),
    ]
