# Generated by Django 2.2.2 on 2021-04-11 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0097_auto_20210405_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['cliente_id'], 'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
    ]
