# Generated by Django 2.2.2 on 2021-04-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0098_auto_20210411_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='dato_contacto_valor',
            field=models.CharField(max_length=25),
        ),
    ]
