# Generated by Django 2.2.2 on 2021-04-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0099_auto_20210411_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudpresupuesto',
            name='contacto',
        ),
        migrations.AddField(
            model_name='solicitudpresupuesto',
            name='contacto',
            field=models.ManyToManyField(to='gestion_imprenta.Contacto'),
        ),
    ]
