# Generated by Django 2.2.2 on 2021-04-18 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0100_auto_20210418_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudpresupuesto',
            old_name='contacto',
            new_name='contactos',
        ),
    ]
