# Generated by Django 2.2.2 on 2021-04-24 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0101_auto_20210418_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordentrabajo',
            options={'ordering': ['-orden_fecha_creacion']},
        ),
    ]
