# Generated by Django 2.2.2 on 2021-04-24 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0102_auto_20210424_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordentrabajoestado',
            options={'ordering': ['-fecha_cambio_estado']},
        ),
    ]
