# Generated by Django 2.2.2 on 2021-04-24 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_imprenta', '0103_auto_20210424_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tarea', models.CharField(choices=[('impresion', 'Impresión'), ('terminaciones', 'Terminaciones'), ('disenio', 'Diseño')], max_length=25)),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.OrdenTrabajo')),
            ],
            options={
                'db_table': '"orden_trabajo_tareas"',
                'ordering': ['orden_trabajo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TareaHistorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flg_realizado', models.BooleanField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.Tarea')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"tarea_historial"',
                'ordering': ['tarea', '-fecha_registro'],
            },
        ),
        migrations.DeleteModel(
            name='Subestado',
        ),
    ]
