# Generated by Django 2.2.2 on 2021-04-25 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0105_tarea_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudpresupuesto',
            name='contactos',
        ),
        migrations.CreateModel(
            name='SolicitudPresupuestoContactos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flg_notificacion', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.Contacto')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.SolicitudPresupuesto')),
            ],
            options={
                'db_table': '"solicitud_presupuesto_contacto"',
            },
        ),
        migrations.AddConstraint(
            model_name='solicitudpresupuestocontactos',
            constraint=models.UniqueConstraint(fields=('solicitud', 'contacto', 'flg_notificacion'), name='unique_contacto_principal'),
        ),
    ]
