# Generated by Django 2.2.2 on 2021-04-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0106_auto_20210425_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpresupuesto',
            name='contactos',
            field=models.ManyToManyField(through='gestion_imprenta.SolicitudPresupuestoContactos', to='gestion_imprenta.Contacto'),
        ),
    ]
