# Generated by Django 2.2.2 on 2021-04-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0107_solicitudpresupuesto_contactos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudpresupuestocontactos',
            name='flg_notificacion',
            field=models.BooleanField(default=False),
        ),
    ]
