# Generated by Django 2.2.2 on 2021-04-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0108_auto_20210425_1123'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='solicitudpresupuestocontactos',
            name='unique_contacto_principal',
        ),
        migrations.AddConstraint(
            model_name='solicitudpresupuestocontactos',
            constraint=models.UniqueConstraint(condition=models.Q(flg_notificacion=True), fields=('flg_notificacion',), name='contacto_principal'),
        ),
    ]
