# Generated by Django 2.2.2 on 2021-04-25 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0109_auto_20210425_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='cliente',
        ),
    ]
