# Generated by Django 2.2.2 on 2021-04-25 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0110_remove_presupuesto_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cantidad',
            options={'ordering': ['cantidad'], 'verbose_name_plural': 'cantidades'},
        ),
    ]
