# Generated by Django 2.2.2 on 2021-04-25 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0111_auto_20210425_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudpresupuesto',
            options={'permissions': [('cambiar_maquina_pliego', 'Puede cambiar máquina pliego')]},
        ),
    ]
