# Generated by Django 2.2.2 on 2021-04-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0112_auto_20210425_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudpresupuesto',
            options={'permissions': [('cambiar_maquina_pliego', 'Puede cambiar máquina pliego'), ('generar_presupuesto', 'Puede generar presupuesto')]},
        ),
        migrations.AlterField(
            model_name='tarea',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
