# Generated by Django 2.2.2 on 2021-05-01 23:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0114_tarea_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='completa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_estimada_fin',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tareahistorial',
            name='campo_actualizado',
            field=models.CharField(default='tes', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tareahistorial',
            name='valor_actualizado',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tareahistorial',
            name='valor_anterior',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
