# Generated by Django 2.2.2 on 2021-05-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0116_auto_20210502_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareahistorial',
            name='flg_realizado',
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
