# Generated by Django 2.2.2 on 2021-05-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0117_auto_20210502_0109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['cliente_id'], 'permissions': [('inactivar_cliente', 'Puede inactivar clientes')], 'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_ulima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
