# Generated by Django 2.2.2 on 2021-05-08 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0118_auto_20210508_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='fecha_ulima_modificacion',
            new_name='fecha_ultima_modificacion',
        ),
    ]
