# Generated by Django 2.2.2 on 2021-05-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0119_auto_20210508_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilio',
            name='fecha_ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
