# Generated by Django 2.2.2 on 2021-05-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0120_domicilio_fecha_ultima_modificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilio',
            name='domicilio_depto',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
