# Generated by Django 2.2.2 on 2021-05-12 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0121_domicilio_domicilio_depto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudpresupuesto',
            name='envio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.Envio'),
        ),
    ]
