# Generated by Django 2.2.2 on 2021-05-23 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0123_auto_20210522_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('provincia_id', models.AutoField(primary_key=True, serialize=False)),
                ('provincia_nombre', models.CharField(max_length=50, unique=True)),
                ('pais', models.CharField(choices=[('argentina', 'Argentina')], max_length=50)),
            ],
            options={
                'db_table': '"provincia"',
            },
        ),
        migrations.RemoveField(
            model_name='domicilio',
            name='pais',
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_imprenta.Provincia'),
        ),
    ]
