# Generated by Django 2.2.2 on 2021-05-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0124_auto_20210523_0020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['cliente_id'], 'permissions': [('inactivar_cliente', 'Inactivar cliente'), ('activar_cliente', 'Activar cliente')], 'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'permissions': [('inactivar_proveedor', 'Puede inactivar proveedor')]},
        ),
        migrations.AlterModelOptions(
            name='serviciotecnico',
            options={'permissions': [('inactivar_servicio_tecnico', 'Inactivar servicio técnico')]},
        ),
        migrations.AlterModelOptions(
            name='trabajo',
            options={'permissions': [('inactivar_trabajo', 'Inactivar trabajo')]},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
