# Generated by Django 2.2.2 on 2021-05-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0125_auto_20210523_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'permissions': [('inactivar_proveedor', 'Inactivar proveedor'), ('activar_proveedor', 'Activar proveedor')]},
        ),
        migrations.AlterModelOptions(
            name='serviciotecnico',
            options={'permissions': [('inactivar_servicio_tecnico', 'Inactivar servicio técnico'), ('activar_servicio_tecnico', 'Activar servicio técnico')]},
        ),
        migrations.AlterField(
            model_name='serviciotecnico',
            name='flg_activo',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
