# Generated by Django 2.2.2 on 2021-05-23 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0126_auto_20210523_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajo',
            options={'permissions': [('inactivar_trabajo', 'Inactivar trabajo'), ('activar_trabajo', 'Activar trabajo')]},
        ),
    ]
