# Generated by Django 2.2.2 on 2021-05-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0128_auto_20210523_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajocantidades',
            name='fecha_ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
