# Generated by Django 2.2.2 on 2021-05-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0129_trabajocantidades_fecha_ultima_modificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajoterminaciones',
            name='fecha_ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
