# Generated by Django 2.2.2 on 2021-05-25 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0131_auto_20210525_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='ultimo_estado',
            field=models.ForeignKey(blank=True, limit_choices_to={'entidad_asociada': 'presupuesto'}, on_delete=django.db.models.deletion.PROTECT, related_name='pres_ultimo_estado', to='gestion_imprenta.Estado'),
        ),
    ]
