# Generated by Django 2.2.2 on 2021-05-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_imprenta', '0132_auto_20210525_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='ultimo_estado',
        ),
        migrations.AddField(
            model_name='solicitudpresupuestocontactos',
            name='flg_activo',
            field=models.BooleanField(default=True),
        ),
    ]
